### ISSUE TITLE
About the pretrain model

### ISSUE THREAD

**Issue by YenanLiu** [GeWu-Lab/Stepping-Stones#1]
Hi authors, 

Thank you for your great work! Could you release the pretrain model for us? I have applied to the authority but have not gotten a reply yet!

**Comment by ucasmjc** [comment]
@YenanLiu Thank you for the reminder! We have replaced those links and opened the access. Additionally, we have updated the rebuilt code of S4 and MS3 subtasks in 'avs/' for easier reproduction and evaluation. Please check our updated readme if you need.
