### ISSUE TITLE
About file save_masks.zip

### ISSUE THREAD

**Issue by KOLE-LE** [GeWu-Lab/Stepping-Stones#2]
Hi, it's a good work!
I find some .png masks in save_masks.zip is corrupted.
Could you provide new and intact file?
Thanks!

**Comment by ucasmjc** [comment]
Thank you for your reminder. The corruption occurred when the file was downloaded from the server to the local machine. I have updated the [link](https://drive.google.com/file/d/1Y0oSJMdudWfYvTuR4z3nhUrBni57uqXt/view?usp=drive_link).

**Comment by KOLE-LE** [comment]
Congratulations on such a good job!

**Comment by KOLE-LE** [comment]
There are still some .png masks is corrupted.
For example, save_masks/v1s/z9NCoRcHSuE_5000_10000/0.png.
