### ISSUE TITLE
save_masks corruption

### ISSUE THREAD

**Issue by KOLE-LE** [GeWu-Lab/Stepping-Stones#3]
There are still some .png masks is corrupted.
For example, save_masks/v1s/z9NCoRcHSuE_5000_10000/0.png.

**Comment by ucasmjc** [comment]
Thanks for your reminder! I have re-downloaded the masks of v1s subset, and update the link.
https://drive.google.com/file/d/1sHvltXub5Ql_ZsVelE1Zt9TpLeb4i3hq/view?usp=drive_link
