### ISSUE TITLE
Unable to download save_masks.zip

### ISSUE THREAD

**Issue by heyuanpengpku** [GeWu-Lab/Stepping-Stones#5]
Great work! Could the author kindly re-upload the save_masks.zip file? The current link is no longer valid. Thank you very much for your help!

**Comment by ucasmjc** [comment]
Thank you for the reminder! When responding to issue #3 , I updated the link and replied within #3 , but I forgot to update the README. The link has now been replaced with the valid one.

**Comment by heyuanpengpku** [comment]
Thanks for your timely reply. I will close this issue.
